version: '3.8'

services:
    #service 1: definition of mysql database
    db:
      image: mysql:latest
      container_name: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=
      ports:
        - "3306:3306"
      restart: always
      volumes:
        - db-data:/var/lib/mysql
      networks:
        - dev




  #service 2: definition of phpMyAdmin
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: my-php-myadmin
      ports:
        - "8082:80"
      restart: always
        
      depends_on:
        - db
      environment:
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD:
      networks:
        - dev



  #service 3: definition of your spring-boot app
    lansrodservice:
      image: lansrod
      container_name: lansrod-app
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "8084:8084"
      restart: always
        
      depends_on:
        - db
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/lansrod_db?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD:
      networks:
        - dev

networks:
    dev:

volumes:
    db-data:
